# Cloud Formation Template
# The environment is an autoscaling, load-balancing environment, 
# with a minimum of two Amazon EC2 instances and a maximum of six.
# Web application is stored on an Amazon S3 bucket. 

AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Application:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: AWS Elastic Beanstalk Workshop Demo Application
  ApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        Ref: Application
      Description: AWS ElasticBeanstalk Application Version
      SourceBundle:
        S3Bucket: "aws-ug-albania-zips"
        S3Key: flask.zip
  ConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:
        Ref: Application
      Description: AWS ElasticBeanstalk Configuration Template
      OptionSettings:
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '2'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '6'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      SolutionStackName: 64bit Amazon Linux 2018.03 v2.9.4 running Python 3.6
  Environment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: Application
      Description: AWS ElasticBeanstalk Environment
      TemplateName:
        Ref: ConfigurationTemplate
      VersionLabel:
        Ref: ApplicationVersion
